### ISSUE TITLE
Regular Expression matching

### ISSUE THREAD

**Issue by Phattboyslim** [lmmfranco/discord-message-handler#1]
Hi,

I came across this package and i really liked it.
I came short of a way to validate with the existing regex i was using.
I made it possible in combination with the minArgs. minArgs will have the validation priority.

Check the updated readme in the file :)

[discord-message-handler.zip](https://github.com/lmmfranco/discord-message-handler/files/3769794/discord-message-handler.zip)

**Comment by lmmfranco** [comment]
Hi! I'm glad you liked it!
Could you please submit these changes as a pull request?

**Comment by Phattboyslim** [comment]
Hey, i will do it this evening when i get home from work this evening. I
will let you know when im done.

Op vr 25 okt. 2019 om 02:27 schreef lmmfranco <notifications@github.com>:
